"groups":
- "name": "wazuh_dashboard.alerts"
  "rules":
  - "alert": "OpenSearchDashboardsNotHealthy"
    "annotations":
      "message": "Server status is not green. The server may be down, it may have lost connection to Opensearch, or may suffer of partial unavailability." 
      "summary": "Server health status is green"
    "expr": |
      absent(kibana_status) == 1 or kibana_status > 0
    "for": "2m"
    "labels":
      "severity": "critical"
  - "alert": "OpenSearchDashboardsLongResponseTime"
    "annotations":
      "message": "The server is up and responsive, however with a high latency."
      "summary": "High response time"
    "expr": |
      kibana_response_average > 200
    "for": "2m"
    "labels":
      "severity": "critical"
  - "alert": "OpenSearchDashboardsNoOpensearchConnection"
    "annotations":
      "message": "Connection to the Opensearch backend is lost."
      "summary": "No connection to Opensearch"
    "expr": |
      absent(kibana_core_es_status) == 1 or kibana_core_es_status > 0
    "for": "2m"
    "labels":
      "severity": "critical"
